# Generated by Django 5.2.12 on 2026-03-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'almacen',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=80, unique=True)),
                ('sitio_web', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
